import os
import pymupdf

docs = {
    "MSG006_OceanicTrade_SI": """SHIPPING INSTRUCTION (SI)
========================================
DOCUMENT REF: SI-OTC-2026-601
BOOKING NO: BK-OTC-2026-601
DATE: 2026-09-18

SHIPPER:
OCEANIC TRADE CORP
SUITE 808, EAST TOWER, 1200 CENTURY AVENUE,
PUDONG, SHANGHAI 200120, CHINA

CONSIGNEE:
ROTTERDAM LOGISTICS DIRECT B.V.
PARKLAAN 24, 3016 BB ROTTERDAM, NETHERLANDS

NOTIFY PARTY:
ROTTERDAM LOGISTICS DIRECT B.V.
PARKLAAN 24, 3016 BB ROTTERDAM, NETHERLANDS

VESSEL & VOYAGE: EVER GIVEN V.045E
PORT OF LOADING: SHANGHAI, CHINA (CNSHA)
PORT OF DISCHARGE: ROTTERDAM, NETHERLANDS (NLRTM)

CONTAINER COUNT: 5 x 40'HC
GROSS WEIGHT: 87,500 KG
COMMODITY: INDUSTRIAL AUTOMATION SENSORS & VALVES

PAYMENT TERMS: FREIGHT PREPAID
DESCRIPTION OF GOODS:
5 X 40' HIGH CUBE CONTAINERS SAID TO CONTAIN
INDUSTRIAL AUTOMATION SENSORS & HYDRAULIC VALVES
CLEAN ON BOARD""",

    "MSG006_OceanicTrade_BL": """BILL OF LADING (DRAFT)
========================================
B/L NUMBER: BL-OTC-2026-601
BOOKING REF: BK-OTC-2026-601
CARRIER: EVERGREEN LINE

SHIPPER:
OCEANIC TRADE CORP
SUITE 808, EAST TOWER, 1200 CENTURY AVENUE,
PUDONG, SHANGHAI 200120, CHINA

CONSIGNEE:
ROTTERDAM LOGISTICS DIRECT B.V.
PARKLAAN 24, 3016 BB ROTTERDAM, NETHERLANDS

NOTIFY PARTY:
ROTTERDAM LOGISTICS DIRECT B.V.
PARKLAAN 24, 3016 BB ROTTERDAM, NETHERLANDS

VESSEL & VOYAGE: EVER GIVEN V.045E
PORT OF LOADING: SHANGHAI (CNSHA)
PORT OF DISCHARGE: ROTTERDAM (NLRTM)

CONTAINER COUNT: 5 x 40'HC
GROSS WEIGHT: 87,500 KG
COMMODITY: INDUSTRIAL AUTOMATION SENSORS & VALVES

FREIGHT STATUS: FREIGHT PREPAID
PARTICULARS FURNISHED BY SHIPPER:
5 CONTAINER(S) 40' HC CONTAINING AUTOMATION SENSORS AND HYDRAULIC VALVES
CLEAN ON BOARD""",

    "MSG007_GlobalTraders_SI": """SHIPPING INSTRUCTION (SI)
========================================
DOCUMENT REF: SI-GT-2026-99214
BOOKING NO: BK-99214
DATE: 2026-09-18

SHIPPER:
GLOBAL TRADERS INC
100 HARBOR DRIVE, SUITE 500,
LONG BEACH, CA 90802, UNITED STATES

CONSIGNEE:
EURO RETAIL LOGISTICS B.V.
COOLHAVEN 110, 3024 AK ROTTERDAM, NETHERLANDS

NOTIFY PARTY:
EURO RETAIL LOGISTICS B.V.
COOLHAVEN 110, 3024 AK ROTTERDAM, NETHERLANDS

VESSEL & VOYAGE: MSC ISABELLA V.240E
PORT OF LOADING: LOS ANGELES, US (USLAX)
PORT OF DISCHARGE: ROTTERDAM, NETHERLANDS (NLRTM)

CONTAINER COUNT: 3 x 40'HC
GROSS WEIGHT: 52,100 KG
COMMODITY: SOLAR PANEL INVERTERS AND MOUNTING HARDWARE

TERMS: FREIGHT PREPAID
DESCRIPTION OF GOODS:
3 X 40' HIGH CUBE CONTAINERS
SOLAR PANEL INVERTERS AND STAINLESS MOUNTING BRACKETS""",

    "MSG007_GlobalTraders_BL": """BILL OF LADING (DRAFT)
========================================
B/L NUMBER: BL-GT-2026-99214
BOOKING REF: BK-99214
CARRIER: MEDITERRANEAN SHIPPING COMPANY (MSC)

SHIPPER:
GLOBAL TRADERS INC
100 HARBOR DRIVE, SUITE 500,
LONG BEACH, CA 90802, UNITED STATES

CONSIGNEE:
EURO RETAIL LOGISTICS B.V.
COOLHAVEN 110, 3024 AK ROTTERDAM, NETHERLANDS

NOTIFY PARTY:
EURO RETAIL LOGISTICS B.V.
COOLHAVEN 110, 3024 AK ROTTERDAM, NETHERLANDS

VESSEL & VOYAGE: MSC ISABELLA V.240E
PORT OF LOADING: LOS ANGELES (USLAX)
PORT OF DISCHARGE: ROTTERDAM, NETHERLANDS (NLRTM)

CONTAINER COUNT: 4 x 40'HC
GROSS WEIGHT: 69,467 KG
COMMODITY: SOLAR PANEL INVERTERS AND MOUNTING HARDWARE

FREIGHT STATUS: FREIGHT PREPAID
PARTICULARS FURNISHED BY SHIPPER:
4 X 40'HC CONTAINERS CONTAINING SOLAR PANEL INVERTERS AND HARDWARE"""
}

target_dirs = [
    os.path.abspath("mock data"),
    os.path.abspath("backend/data/attachments")
]

for name, text in docs.items():
    doc = pymupdf.open()
    page = doc.new_page(width=595, height=842) # A4 size
    margin = 50
    rect = pymupdf.Rect(margin, margin, 595 - margin, 842 - margin)
    page.insert_textbox(rect, text, fontsize=11, fontname="Courier")
    
    for tdir in target_dirs:
        os.makedirs(tdir, exist_ok=True)
        pdf_path = os.path.join(tdir, f"{name}.pdf")
        doc.save(pdf_path)
        print(f"Generated PDF: {pdf_path}")
    doc.close()
